#!/usr/bin/python
#  Print sun's altitude and azimuth coordinates
#  for a given date, time (hours UT), latitude, and longitude:
#     YYYY MM DD HH LAT LON
from sunpos import time_and_location_to_sun_alt_azimuth
from sys import argv
print "Sun altitude angle: {:f}, azimuth angle: {:f}".format(
	*time_and_location_to_sun_alt_azimuth(
		*map(int, argv[1:7])
	)
)
# ./altazi 1990 4 19 0 60 15
# Sun altitude angle: 342.042994, azimuth angle: 15.676697
