#!python
#  Print sun's celestial coordinates for a given date: YYYY MM DD
from sys import argv
from sunpos import date_to_sun_earth_ecliptic, Date
from sunpos import sun_earth_ecliptic_to_celestial
date = Date(int(argv[1]), int(argv[2]), int(argv[3]))
d, l, _, o = date_to_sun_earth_ecliptic(date)
celestial = sun_earth_ecliptic_to_celestial(d, l, o)
print(f"Sun dist: {d:f}, right ascension: {celestial.RA:f}, declination: {celestial.Decl:f}")
# ./celest 1990 4 19
# Sun dist: 1.004323, right ascension: 26.658078, declination: 11.008375
